# ───────── nixpacks.toml ─────────
# Multi-stage style build → tiny runtime layer

[phases.install]
cmds = [
  # stop Puppeteer & friends downloading 100-MB binaries
  "export PUPPETEER_SKIP_DOWNLOAD=1",
  "pnpm install --frozen-lockfile",
  "pnpm approve-builds esbuild @swc/core"
]

[phases.build]
cmds = [
  # client ⬇️
  "pnpm run build:client",
  # server ⬇️
  "npx tsc -p tsconfig.server.json",
  # throw dev deps overboard
  "pnpm prune --prod"
]

[phases.build]
dependsOn = ["install"]        # explicit, just for clarity

# ───── Runtime: fresh, lean layer ─────
[start]
runImage = "gcr.io/distroless/nodejs20-debian11"  # ~55 MB
onlyIncludeFiles = [
  "dist",          # compiled server + static assets
  "node_modules",  # *prod-only* deps after prune
  "package.json"   # so Node can resolve exports
]
cmd = "node dist/server/index.js"

[variables]
PORT = "3000"
# ───────── end ─────────
