[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.5",
    "paddleocr>=2.10.0",
    "paddlepaddle>=3.0.0",
    "pdf2image>=1.17.0",
    "pillow>=11.2.1",
]
