CREATE TABLE "appointment_settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"time_interval" integer DEFAULT 30 NOT NULL,
	"max_concurrent_inbound" integer DEFAULT 2 NOT NULL,
	"max_concurrent_outbound" integer DEFAULT 2 NOT NULL,
	"share_availability_info" boolean DEFAULT true NOT NULL,
	"sunday" boolean DEFAULT false NOT NULL,
	"monday" boolean DEFAULT true NOT NULL,
	"tuesday" boolean DEFAULT true NOT NULL,
	"wednesday" boolean DEFAULT true NOT NULL,
	"thursday" boolean DEFAULT true NOT NULL,
	"friday" boolean DEFAULT true NOT NULL,
	"saturday" boolean DEFAULT false NOT NULL,
	"sunday_start_time" text DEFAULT '08:00',
	"sunday_end_time" text DEFAULT '17:00',
	"monday_start_time" text DEFAULT '08:00',
	"monday_end_time" text DEFAULT '17:00',
	"tuesday_start_time" text DEFAULT '08:00',
	"tuesday_end_time" text DEFAULT '17:00',
	"wednesday_start_time" text DEFAULT '08:00',
	"wednesday_end_time" text DEFAULT '17:00',
	"thursday_start_time" text DEFAULT '08:00',
	"thursday_end_time" text DEFAULT '17:00',
	"friday_start_time" text DEFAULT '08:00',
	"friday_end_time" text DEFAULT '17:00',
	"saturday_start_time" text DEFAULT '08:00',
	"saturday_end_time" text DEFAULT '17:00',
	"sunday_break_start_time" text DEFAULT '12:00',
	"sunday_break_end_time" text DEFAULT '13:00',
	"monday_break_start_time" text DEFAULT '12:00',
	"monday_break_end_time" text DEFAULT '13:00',
	"tuesday_break_start_time" text DEFAULT '12:00',
	"tuesday_break_end_time" text DEFAULT '13:00',
	"wednesday_break_start_time" text DEFAULT '12:00',
	"wednesday_break_end_time" text DEFAULT '13:00',
	"thursday_break_start_time" text DEFAULT '12:00',
	"thursday_break_end_time" text DEFAULT '13:00',
	"friday_break_start_time" text DEFAULT '12:00',
	"friday_break_end_time" text DEFAULT '13:00',
	"saturday_break_start_time" text DEFAULT '12:00',
	"saturday_break_end_time" text DEFAULT '13:00',
	"sunday_max_appointments" integer DEFAULT 0,
	"monday_max_appointments" integer DEFAULT 0,
	"tuesday_max_appointments" integer DEFAULT 0,
	"wednesday_max_appointments" integer DEFAULT 0,
	"thursday_max_appointments" integer DEFAULT 0,
	"friday_max_appointments" integer DEFAULT 0,
	"saturday_max_appointments" integer DEFAULT 0,
	"default_buffer_time" integer DEFAULT 0 NOT NULL,
	"default_grace_period" integer DEFAULT 15 NOT NULL,
	"default_email_reminder_time" integer DEFAULT 24 NOT NULL,
	"allow_appointments_through_breaks" boolean DEFAULT false NOT NULL,
	"allow_appointments_past_business_hours" boolean DEFAULT false NOT NULL,
	"facility_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "appointment_types" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"facility_id" integer NOT NULL,
	"duration" integer NOT NULL,
	"color" text NOT NULL,
	"type" text NOT NULL,
	"show_remaining_slots" boolean DEFAULT true NOT NULL,
	"grace_period" integer DEFAULT 15 NOT NULL,
	"buffer_time" integer DEFAULT 0 NOT NULL,
	"max_appointments_per_day" integer,
	"max_concurrent" integer DEFAULT 1 NOT NULL,
	"email_reminder_time" integer DEFAULT 24 NOT NULL,
	"allow_appointments_through_breaks" boolean DEFAULT false NOT NULL,
	"allow_appointments_past_business_hours" boolean DEFAULT false NOT NULL,
	"override_facility_hours" boolean DEFAULT false NOT NULL,
	"timezone" text DEFAULT 'America/New_York',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "assets" (
	"id" serial PRIMARY KEY NOT NULL,
	"filename" text NOT NULL,
	"description" text,
	"file_type" text,
	"file_size" integer,
	"url" text NOT NULL,
	"tags" jsonb,
	"uploaded_by" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_accessed_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "booking_pages" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"welcome_message" text,
	"confirmation_message" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"facilities" jsonb NOT NULL,
	"excluded_appointment_types" jsonb,
	"use_organization_logo" boolean DEFAULT true NOT NULL,
	"custom_logo" text,
	"primary_color" text DEFAULT '#4CAF50',
	"created_by" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp,
	"last_modified_by" integer,
	CONSTRAINT "booking_pages_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "carriers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"mc_number" text,
	"contact_name" text,
	"contact_email" text,
	"contact_phone" text,
	CONSTRAINT "carriers_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "company_assets" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"manufacturer" text NOT NULL,
	"owner" text NOT NULL,
	"department" text,
	"category" text NOT NULL,
	"barcode" text,
	"serial_number" text,
	"description" text,
	"purchase_price" text,
	"currency" text DEFAULT 'USD',
	"purchase_date" date,
	"warranty_expiration" date,
	"depreciation" text,
	"asset_value" text,
	"location" text DEFAULT 'warehouse',
	"status" text DEFAULT 'active',
	"template" text,
	"tags" jsonb,
	"model" text,
	"condition" text,
	"notes" text,
	"manufacturer_part_number" text,
	"supplier_name" text,
	"po_number" text,
	"vendor_information" text,
	"photo_url" text,
	"document_urls" jsonb,
	"last_maintenance_date" date,
	"next_maintenance_date" date,
	"maintenance_schedule" text,
	"maintenance_contact" text,
	"maintenance_notes" text,
	"implementation_date" date,
	"expected_lifetime" text,
	"certification_date" date,
	"certification_expiry" date,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_by" integer,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE "custom_questions" (
	"id" serial PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"type" text NOT NULL,
	"is_required" boolean DEFAULT false NOT NULL,
	"placeholder" text,
	"options" jsonb,
	"default_value" text,
	"order" integer NOT NULL,
	"appointment_type_id" integer,
	"applicable_type" text DEFAULT 'both',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "daily_availability" (
	"id" serial PRIMARY KEY NOT NULL,
	"appointment_type_id" integer NOT NULL,
	"day_of_week" integer NOT NULL,
	"is_available" boolean DEFAULT true NOT NULL,
	"max_appointments" integer DEFAULT 0 NOT NULL,
	"start_time" text DEFAULT '08:00' NOT NULL,
	"end_time" text DEFAULT '17:00' NOT NULL,
	"break_start_time" text DEFAULT '12:00',
	"break_end_time" text DEFAULT '13:00',
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "docks" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"facility_id" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"type" text NOT NULL,
	"custom_type" text,
	"constraints" jsonb
);
--> statement-breakpoint
CREATE TABLE "facilities" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"address1" text NOT NULL,
	"address2" text,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"pincode" text NOT NULL,
	"country" text NOT NULL,
	"latitude" text,
	"longitude" text,
	"company" text,
	"timezone" text DEFAULT 'America/New_York',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "holidays" (
	"id" serial PRIMARY KEY NOT NULL,
	"date" date NOT NULL,
	"description" text NOT NULL,
	"scope" text NOT NULL,
	"facility_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"type" text NOT NULL,
	"related_schedule_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schedules" (
	"id" serial PRIMARY KEY NOT NULL,
	"dock_id" integer,
	"carrier_id" integer NOT NULL,
	"appointment_type_id" integer,
	"truck_number" text NOT NULL,
	"trailer_number" text,
	"driver_name" text,
	"driver_phone" text,
	"driver_email" text,
	"customer_name" text,
	"carrier_name" text,
	"mc_number" text,
	"bol_number" text,
	"po_number" text,
	"pallet_count" text,
	"weight" text,
	"appointment_mode" text DEFAULT 'trailer',
	"start_time" timestamp NOT NULL,
	"end_time" timestamp NOT NULL,
	"actual_start_time" timestamp,
	"actual_end_time" timestamp,
	"type" text NOT NULL,
	"status" text NOT NULL,
	"notes" text,
	"custom_form_data" jsonb,
	"created_by" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_modified_at" timestamp,
	"last_modified_by" integer
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"email" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"role" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
