name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # ① Checkout
    - uses: actions/checkout@v4

    # ② Mount secrets from Doppler
    - name: Load secrets
      uses: dopplerhq/cli-action@v2
      with:
        token: ${{ secrets.DOPPLER_SERVICE_TOKEN }}
        project: dock-optimizer-prod
        config: ${{ github.ref == 'refs/heads/main' && 'prd' || 'preview' }}
        mount: true

    # ③ Install pnpm first
    - uses: pnpm/action-setup@v2
      with:
        version: 10.13.1
        run_install: false

    # ④ Node 20 + pnpm cache
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: pnpm
    - run: corepack enable

    # ⑤ Local Postgres
    - uses: ikalnytskyi/action-setup-postgres@v7
      with:
        postgres-version: '15'
        username: test
        password: test
        database: dock_opt_test
    - run: echo \"DATABASE_URL=postgres://test:test@localhost:5432/dock_opt_test\" >> $GITHUB_ENV

    # ⑥ Install deps
    - run: pnpm install --frozen-lockfile

    # ⑦ Build once (tsc + vite) so dist/** exists
    - run: pnpm run build

    # ⑧ Tests, lint, types
    - run: pnpm run test:ci
    - run: pnpm run lint
    - name: Type check
      run: pnpm run typecheck --if-present
